# Generated by Django 6.0.2 on 2026-05-04 19:22

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_slug_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cuerpo',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
