# Generated by Django 6.0.2 on 2026-03-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='resumen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
