# Generated by Django 6.0.2 on 2026-03-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_imagen_principal_alter_post_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cuerpo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
